Edit admin page
abeshi03/office_spa pull request #27
Opened 2020-11-24 02:48 UTC by abeshi03

# 変更点
### ユーザーページと管理者ページの差別化がなかったので変更
- 予約機能のデフォルトの時間を設定しUIを向上
- ログイン後のトップページのリンク先の変更
- 管理者は過去の予約以外の一覧が見れ、削除が行える
- テストの追加

# 関連issues
#26 

お世話になっております。

管理者ページの変更を実装致しました。
コードの補足をコメントにて記述しております。

このような御機会を頂き本当にありがとうございます。
ご多忙の中、大変恐縮ではございますがレビュー宜しくお願い申し上げます。

2020-11-24 03:19 UTC, aretoky requested changes
@abeshi03 ざっとコードレビューしてみましたー。確認ください!👍

2020-11-24 03:19 UTC, aretoky commented on .rubocop.yml
>      - 'node_modules/**/*'
[Ruby - なぜ最終行に改行を入れるのですか？｜teratail](https://teratail.com/questions/71778)
に従いましょう。
以下の設定すれば今後は意識しなくてできます。
[ファイル末尾をつねに改行で終端させる IntelliJ 系の設定 - Qiita](https://qiita.com/tanakahisateru/items/66359b6217e7ac728856)

2020-11-24 03:19 UTC, aretoky commented on app/controllers/reservations_controller.rb
> +    @reservations_index = Reservation.paginate(page: params[:page]).
細かいことですが、`Reservation.paginate(page: params[:page])`が重複しているのでまとめてもいいかもしれません。

2020-11-24 03:19 UTC, aretoky commented on app/views/layouts/_footer.html.erb
> +        <h4 class="user-footer-link"><%= current_user.admin? ? "ユーザー一覧" : "マイページ" %></h4>
viewでロジックを書くところではないので、条件分岐は最小限にしましょう。
`current_user.admin?`の条件分岐一回でかけそうですね 😄

2020-11-24 03:19 UTC, aretoky commented on app/controllers/reservations_controller.rb
> +      where("start_time > ?", Date.today).order(start_time: :desc)
whereやorderはできれば、Modelのscopeで書いたほうがいいです。Modelでテストできるようになるからです。
細かいこと含めControllerを太らせないことが初心者脱出の第一歩です。

2020-11-24 11:41 UTC, abeshi03 commented on app/views/layouts/_footer.html.erb
> +        <h4 class="user-footer-link"><%= current_user.admin? ? "ユーザー一覧" : "マイページ" %></h4>
レビューありがとうございます。
if elseの一回の条件分岐で修正致しました。

2020-11-24 11:43 UTC, abeshi03 commented on app/controllers/reservations_controller.rb
> +    @reservations_index = Reservation.paginate(page: params[:page]).
レビューありがとうございます。
dry原則にしたがい重複コードがないよう意識してまいります。

2020-11-24 11:55 UTC, abeshi03 commented on .rubocop.yml
>      - 'node_modules/**/*'
レビューありがとうございます。
改行については普段あまり意識していなかったのでとても勉強になりました！

2020-11-24 13:31 UTC, abeshi03 reviewed
Reservations.paginateの重複部分をなくしmodelにorderやwhereのscopeを定義致しました。
普段controllerに定義してしまうことが多かったためQiitaにアウトプット致しました。
https://qiita.com/kohei_abe/items/8afbeec0bf422c01a52f

2020-11-25 01:19 UTC, aretoky requested changes
@abeshi03 
レビューしました。
テストちゃんと書こうという姿勢いいですね！ 😄 

rubocopを実行してない形跡があるので走らせた方がいいですね。
焦ってたりするとrubocop実行忘れたりするので、sider入れると自動でやってくれるので楽ですよー。

2020-11-25 01:19 UTC, aretoky commented on app/views/static_pages/_top.html.erb
>  </div>
前回と同様にファイル末尾問題ですね。

2020-11-25 01:19 UTC, aretoky commented on spec/support/select_date_helper.rb
> +    select day,   :from => "#{base_id}_3i"
```suggestion
    select month, from: "#{base_id}_2i"
    select day,  from: "#{base_id}_3i"
```

2020-11-25 01:19 UTC, aretoky commented on spec/support/select_date_helper.rb
> +end
前回と同様にファイル末尾問題ですね。

2020-11-25 01:19 UTC, aretoky commented on app/views/reservations/_form.html.erb
> +    <%= f.datetime_select :start_time, {default: Date.today + 19.hour + 15.minute, minute_step: 15} %>
```suggestion
    <%= f.datetime_select :start_time, { default: Date.today + 19.hour + 15.minute, minute_step: 15 } %>
```
rubocop漏れかな?

2020-11-25 12:17 UTC, abeshi03 commented
お世話になっております。
ご多忙の中、レビュー本当にありがとうございました。

ファイルの末尾問題に関して、見直すとviewなどで
かなり出て来ましたので修正しております。

ご多忙の中大変恐縮ではございますが、宜しくお願い申し上げます。

2020-11-25 13:00 UTC, aretoky approved these changes
@abeshi03 LGTM!

2020-11-25 14:02 UTC, merged