Association user and reservation
abeshi03/office_spa pull request #30
Opened 2020-11-25 17:49 UTC by abeshi03

# 変更点
- ユーザーテーブルと予約テーブルを関連付け
- ユーザー詳細ぺーじに予約履歴を表示
- ユーザー詳細ページから自分の予約であれば削除ができる
- テストの追加

# 関連issues
#29 

お世話になっております。
ユーザーテーブルと予約テーブルの関連付けを実装致しました。

ご多忙の中、大変恐縮ではございますが
レビュー宜しくお願い申し上げます。

2020-11-25 17:59 UTC, abeshi03 commented on app/controllers/users_controller.rb
> +    @reservations = @user.reservations.reservations_history(10)
モデルにメソッドを定義致しました。

2020-11-25 18:08 UTC, abeshi03 commented on app/models/reservation.rb
> +  scope :reservations_history, -> (count) { order(start_time: :desc).limit(count) }
limitは引数で定義し柔軟性を意識し実装致しました。

2020-11-25 18:09 UTC, abeshi03 commented on app/controllers/users_controller.rb
> +    @reservations = @user.reservations.reservations_history(10)
モデルにメソッドを定義しております。

2020-11-25 18:10 UTC, abeshi03 commented on spec/models/reservation_spec.rb
> +    end
引数が実際の予約数より多い場合と少ない場合でテストしております。

2020-11-25 18:11 UTC, abeshi03 commented on app/views/users/show.html.erb
> +<% if current_user %>
自分自身であれば予約の履歴とキャンセルができるよう実装致しました。

2020-11-26 01:12 UTC, aretoky requested changes
@abeshi03 レビューしましたー。`current_user.id`の扱いは大事ですー。

2020-11-26 01:12 UTC, aretoky commented on db/migrate/20201125142228_add_user_id_to_reservations.rb
> +    add_column :reservations, :user_id, :integer
`user_id`はインデックス付けないと遅くなりますね。付けましょう。

2020-11-26 01:12 UTC, aretoky commented on app/models/user.rb
> +  # 管理者が誤って削除された場合メニューが全て削除されては困るのでdependentはつけない
こういうコメントはいいですね

2020-11-26 01:12 UTC, aretoky commented on app/views/reservations/_form.html.erb
> +  <%= f.hidden_field :user_id, value: current_user.id %>
`current_user.id`はフォームで渡す必要ないですねー。
フォームで渡してしまうと、悪意ある第三者に別のuser_idを渡せされるセキュリティリスクをはらみます。これ仕事でやると死ぬやつです。
なので`current_user.id`はフォームで渡さず、controllerで`current_user.id`を設定しましょうー。

2020-11-27 02:48 UTC, abeshi03 commented
# 変更点
- user_idにindexを追加
- current_user.idをコントローラーに記述

お世話になっております。
ご多忙の中、レビュー頂き
本当にありがとうございます。
ご指摘頂きましたところを修正致しました。

ご多忙の中、大変恐縮ではございますが、
レビュー宜しくお願い申し上げます。

2020-11-27 11:32 UTC, abeshi03 commented
## 変更点
- セキュリティリスクと無駄なパラメーターを渡すことのリスクの回避
- controllerのリファクタリング

## 備考
default_scopeを使ってcontrollerをすっきりとできる箇所が
いくつかありますのでなるべくcontorllerを痩せさせられるようmodelに記述致しました。

お世話になっております。
ご指摘頂きました部分や改善できそうな部分を修正致しました。
ご多忙の中、大変恐縮ではございますが、宜しくお願い申し上げます。

2020-11-28 09:21 UTC, aretoky approved these changes
@abeshi03 LGTM!

2020-11-28 11:38 UTC, merged