Association reservation and menu
abeshi03/office_spa pull request #33
Opened 2020-11-29 17:15 UTC by abeshi03

##  変更点
- menuテーブルとreservationテーブルを関連付け
- 予約作成画面にselect_boxでメニューを追加
- メニューを選んで予約ができるかテスト

## 関連issuse
#32 

お世話になっております。
メニューテーブルと予約テーブルの関連付けを行いました。
ご多忙の中大変恐縮ではございますが、
宜しくお願い申し上げます。

2020-11-29 17:20 UTC, abeshi03 commented on app/views/reservations/_form.html.erb
> +  <!-- 繰り返し処理をするとselect_boxが3つできてしまうため一つずつ記述 -->
繰り返し処理だとselect_boxが3つできてしまい、今回は一つのselect_boxにメニューを選べるようにしたかったためこのような記述に致しました。

2020-11-29 17:20 UTC, abeshi03 commented on spec/system/reservations_spec.rb
> +      end
メニューが選択されていない場合失敗するテストです。

2020-11-29 17:20 UTC, abeshi03 commented on spec/system/reservations_spec.rb
> +      end
メニューが登録され予約が成功するテスト。

2020-12-01 02:01 UTC, aretoky requested changes
@abeshi03 一点コメントしましたー

2020-12-01 02:01 UTC, aretoky commented on app/views/reservations/_form.html.erb
> +      [menus.third.name,  menus.third.id]],
```suggestion
      menus.first(3).map { |menu| [menu.name, menu.id] },
```
で多分いけますね。

2020-12-01 02:18 UTC, aretoky commented
@abeshi03 PRで補足コメント分かりやすいですね。さらにコードにコメントとして書いておくとPR読む以外のときにも読めて良いと思います。

2020-12-01 23:13 UTC, abeshi03 commented on app/views/reservations/_form.html.erb
> +  <!-- セレクトボックスで全てのメニューを配列で取得 -->
全てのmenuのデータをとってきたかったためmapのみで配列を取得致しました！

2020-12-01 23:16 UTC, abeshi03 commented
お世話になっております。
ご多忙の中、レビュー頂き本当にありがとうございます。

mapで配列を取ってくると綺麗に表示できました、、、
とても勉強になったためブログでアウトプット致しました。
https://qiita.com/kohei_abe/items/77b063bd26d873449103

ご多忙の中大変恐縮ではございますが、宜しくお願い申し上げます。

2020-12-02 01:50 UTC, aretoky approved these changes
@abeshi03 LGTM! 👍

2020-12-02 12:52 UTC, merged