Reservation history
abeshi03/office_spa pull request #35
Opened 2020-12-03 15:17 UTC by abeshi03

# 変更点
- ユーザー詳細ページに予約メニューの履歴を追加
- それに伴ったテストの追加とリファクタリング

# 関連issues
#34

2020-12-03 15:18 UTC, abeshi03 commented on app/views/users/show.html.erb
> +            <!-- メニューテーブルと予約テーブルを後から関連付けしたため過去の予約のメニューがnil classになるのを防ぐため条件分岐 -->
関連付けのする前のデータがmenu_idがnilになってしまっているため条件分岐を記述致しました。

2020-12-03 15:19 UTC, abeshi03 commented on app/views/users/show.html.erb
> +<%= render "reservations_history", reservaions: @reservations %>
詳細ページの記述量が多くなりみにくいと感じたため、パーシャル化致しました。

2020-12-03 15:22 UTC, abeshi03 commented on spec/support/reservation_support.rb
> +  def create_reservation
テストのコード量が多くなってしまうためspec/supportでリファクタリング致しました。

2020-12-03 15:22 UTC, abeshi03 commented on spec/system/reservations_spec.rb
> +        create_reservation
spec/supportの予約が成功するメソットで定義。

2020-12-04 02:02 UTC, aretoky requested changes
@abeshi03 レビューしましたー!

2020-12-04 02:02 UTC, aretoky commented on spec/support/reservation_support.rb
> +  def create_reservation
参考
[テストコードの期待値はDRYを捨ててベタ書きする ～テストコードの重要な役割とは？～ - Qiita](https://qiita.com/jnchito/items/eb3cfa9f7db752dcb796)

2022-01-03 12:36 UTC, merged